#!/usr/bin/env bash
#
# Convert an mp3 file to raw pcm 44100 s16le format (to stdout).
#
# Usage: mp3-to-raw <mp3-file>
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: September 04, 2021
# License: MIT

. ./lib/utils || exit 1

mp3=$1
samplerate='44100'
channels=2

[[ -n $mp3 ]] || fatal "Usage: ${0##*/} <mp3-file>"

exec ffmpeg \
	-hide_banner -nostdin -loglevel error \
	-i "$mp3" \
	-f s16le -acodec pcm_s16le \
	-ac "$channels" -ar "$samplerate" \
	-
